---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-provider-aws
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: crossplane-system
  path: ./infra/crossplane-provider-aws
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
