---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-provider-jet-aws-config
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: crossplane-system
    - name: crossplane-provider-jet-aws
  path: ./infra/crossplane-provider-jet-aws-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
