---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: crossplane-stable
  namespace: flux-system
spec:
  url: https://charts.crossplane.io/stable
  interval: 10m0s
  timeout: 1m0s
