---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 5m
  chart:
    spec:
      chart: crossplane
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: crossplane-values
