apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
- namespace.yaml
- crossplane.yaml
# - aws-credentials.yaml
# - jet-aws-credentials.yaml
configMapGenerator:
- name: crossplane-values
  files:
    - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
